api/urls.py
from django.urls import path
from .views import CurrencyList, SymbolList, RateList
from .views import api_rate, api_currency_detail, api_rate_historical_from, api_rate_historical_range, api_convert
from .views import api_rate_historical_post, api_currency_update

app_name = 'api'

urlpatterns = [
    path('symbols/', SymbolList.as_view()),
    path('latest/', CurrencyList.as_view()),
    path('latest/<str:currency_code>/', api_currency_detail, name="detail"),
    path('rates/', RateList.as_view()),
    path('create/', api_rate_historical_post, name="create"),
    path('update/<str:currency_code>/', api_currency_update, name="edit"),
    path('rates/<str:rate_code>/', api_rate),
    path('rates/<str:rate_code>/<int:rate_from>/', api_rate_historical_from),
    path('rates/<str:rate_code>/<int:rate_from>/<int:rate_to>/', api_rate_historical_range),
    path('convert/<str:rate_code_from>/<str:rate_code_to>/<int:amount>/', api_convert),
]

banking_system/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

API_TITLE = 'Currency API'
API_DESCRIPTION = 'A web API for creating and editing blog posts.'
schema_view = get_schema_view(title="Blog API")

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),
    # Apps
    path('auth/', include('auth_app.urls')),
    path('transaction/', include('transaction_app.urls')),
    path('account/', include('accounts_app_account.urls')),
    path('employee/', include('employee_app.urls')),
    # path('auth/', include('django.contrib.auth.urls')),
    path('chat/', include('chat.urls')),
    # API
    path('api/v1/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    # Task queues
    path('celery-progress/', include('celery_progress.urls')),
    #MFA
    path('settings/', include('django_mfa.urls')),
    # Documentation
    path('documentation/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION))
]

employee_app/urls.py
from django.urls import path
from . import views
from auth_app.views import login,signup
# from django.views.generic import RedirectView
app_name = 'employee_app'

urlpatterns = [
    path('overview_customers/', views.overview_customers, name='overview_customers'),
    path('edit_customer/<int:customer_id>/', views.edit_customer, name='edit_customer'),
    path('edit_customer_account/<int:customer_id>/<int:customer_account_id>/' , views.edit_customer_account, name='edit_customer_account'),
    path('create_customer/', views.create_customer, name='create_customer'),
    path('create_customer_account/', views.create_customer_account, name='create_customer_account'),
    path('login/', login, name='employee_login'),
    path('signup/', signup, name='employee_signup'),
    # path('login/', RedirectView.as_view(pattern_name='auth_app:login')),
    # path('signup/', RedirectView.as_view(pattern_name='auth_app:signup')),
]

employee_app/models.py
from django.db import models

employee_app/forms.py
from django import forms

class CustomerFormCreateValidation(forms.Form):
    RANK_CHOICES = [
        ('gold', 'Gold'),
        ('silver', 'Silver'),
        ('bronze', 'Bronze')
    ]

    username = forms.CharField(min_length=10, required=True)
    first_name = forms.CharField(min_length=5, required=True)
    last_name = forms.CharField(min_length=5, required=True)
    email = forms.CharField(min_length=10, required=True)
    customer_rank = forms.ChoiceField(choices=RANK_CHOICES)
    customer_phone_number = forms.CharField(min_length=10, required=True, max_length=20)
    customer_has_loan = forms.BooleanField(required=False, widget=forms.CheckboxInput)

    # class Meta:
    #     fields = '__all__'

class CustomerFormEditValidation(forms.Form):
    RANK_CHOICES = [
        ('gold', 'Gold'),
        ('silver', 'Silver'),
        ('bronze', 'Bronze')
    ]

    id = forms.IntegerField(required=True)
    email = forms.CharField(min_length=10, required=True)
    customer_rank = forms.ChoiceField(choices=RANK_CHOICES)
    customer_phone_number = forms.CharField(min_length=10, required=True, max_length=20)
    customer_has_loan = forms.BooleanField(required=False, widget=forms.CheckboxInput)

class AccountFormCreateValidation(forms.Form):
    account_user_fk = forms.IntegerField(required=True)
    account_balance = forms.DecimalField(decimal_places=2, max_digits=7, required=True)

employee_app/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from auth_app.models import Profile
from accounts_app_account.models import Account
from django.contrib.auth.models import User
from django.db import transaction, DatabaseError
from .forms import CustomerFormCreateValidation, CustomerFormEditValidation, AccountFormCreateValidation
from transaction_app.models import Loan, Transaction
from django.contrib.admin.views.decorators import staff_member_required

import random
import string

@staff_member_required
def overview_customers(request):
    # Todo: Add transactions and payments
    # Todo: Add in base.html employee navigation
    context = {
        'customers': Profile.objects.all(),
        'accounts': Account.objects.all(),
    }

    # print(context)

    return render(request, 'employee_app/overview_customers.html', context)

@staff_member_required
def edit_customer(request, customer_id):
    customer_id = int(customer_id)
    context = {}
    try:
        customer = Profile.objects.get(id=customer_id)
    except Profile.DoesNotExist:
            # Todo: Add context with errors
            return overview_customers(request)

    # try:
    #     user = User.objects.get(customer)
    # except User.DoesNotExist:
    #         # Todo: Add context with errors
    #         return overview_customers(request)


    # GET method for populating form
    if request.method == 'GET':
        context = {
            'customer': customer,
        }

    # POST method for editing user
    if request.method == 'POST':
        customerForm = CustomerFormEditValidation(request.POST)
        if customerForm.is_valid():
            # Todo: Check if passwords match
            customer.user.email = request.POST['email']

            customer.customer_rank = request.POST['customer_rank']
            customer.customer_phone_number = request.POST['customer_phone_number']
            post_loan = request.POST.get('customer_has_loan', False)
            post_loan = True if post_loan == 'on' else False
            customer.customer_has_loan = post_loan
            
            try:
                with transaction.atomic():
                    customer.save()
                
                context = {
                    'customers': Profile.objects.all(),
                    'accounts': Account.objects.all(),
                    'edited_user': customer
                }

                return render(request, 'employee_app/overview_customers.html', context)
            except DatabaseError:
                # Todo: print error message
                return render(request, 'employee_app/create_customer.html')
        else:
            context = {
                'customer': customer,
                'customerFormErrors': customerForm
            }      
            

    return render(request, 'employee_app/edit_customer.html', context)

@staff_member_required
def create_customer(request):

    context = {}

    if request.method == "POST":
        customerForm = CustomerFormCreateValidation(request.POST)
        if customerForm.is_valid():
            print()
            # Todo: Check if form valid & form fields not empty
            # Todo: Validate against existing username in DB
            post_username = request.POST['username']
            post_fname = request.POST['first_name'] 
            post_lname = request.POST['last_name']
            # Todo: Check if passwords match
            post_email = request.POST['email']
            post_password = request.POST['password1']
            post_rank = request.POST['customer_rank']
            post_phone = request.POST['customer_phone_number']
            post_loan = request.POST.get('customer_has_loan', False)
            post_loan = True if post_loan == 'on' else False
            # post_loan = True if request.POST['customer_has_loan'] == 'on' else False

            try:
                with transaction.atomic():
                    # create_user() hashes the password
                    user = Profile.create_customer(post_email, post_username, post_password, post_fname, post_lname)

                    # create() does not hash 
                    profile = Profile.create_profile(user, post_phone, '123token', False, post_loan)


                # Test exception:
                # if exception:
                #     raise exception

                # Todo: render overview customers with context     
                context = {
                    'customers': Profile.objects.all(),
                    'accounts': Account.objects.all(),
                    'new_user': user
                }

                return render(request, 'employee_app/overview_customers.html', context)
            except DatabaseError:
                # Todo: print error message
                return render(request, 'employee_app/create_customer.html')
                
                # print(DatabaseError)
                # pass
        else:
            context = {
                'customerFormErrors': customerForm
            }

    return render(request, 'employee_app/create_customer.html', context)

@staff_member_required
def edit_customer_account(request, customer_id, customer_account_id):
    customer_id = int(customer_id)
    account_id = int(customer_account_id)
    # Todo: add payments
    context = {}

    # myLoanUsername
    # mypassword123
    try:
        customer = Profile.objects.get(id=customer_id)
        account = Account.objects.get(id=account_id)
        loans = Loan.objects.filter(loan_account_fk=customer)
        transactions = Transaction.objects.filter(transaction_user_account_fk=account)
    # Multiple exceptions are handled in a tuple
    except (Profile.DoesNotExist, Account.DoesNotExist):
        # Todo: Add context with errors
         return overview_customers(request)

    # GET method for populating form
    if request.method == 'GET':
        # Lambda is the anonymous fc equiv. in python
        # List() is necessary due to list comprehensions and python3.x
        context = {
            'customer': customer,
            'account': account,
            'transactions': transactions,
            'loansFinished': list(filter(lambda x: x.is_ongoing() == 0, loans)),
            'loansOngoing': list(filter(lambda x: x.is_ongoing() == 1, loans))
        }

    # POST method for modifying balance
    if request.method == 'POST':
        post_balance = request.POST['account_balance']

        # Todo: validate post_balance
        account.account_balance = post_balance
        account.save()

        context = {
            'customers': Profile.objects.all(),
            'accounts': Account.objects.all(),
            'edited_account': account
        }

        return render(request, 'employee_app/overview_customers.html', context)

    return render(request, 'employee_app/edit_customer_account.html', context)

@staff_member_required
def create_customer_account(request):
    if request.method == 'GET':
        context = {
            'customers': Profile.objects.all()
        }

    if request.method == 'POST':
        try:
            customer = Profile.objects.get(id=request.POST['account_user_fk'])
            accountForm = AccountFormCreateValidation(request.POST)
            print(accountForm)
            if accountForm.is_valid():
                try:
                    letters = string.digits
                    value = ( ''.join(random.choice(letters) for i in range(20)) )
                    
                    account = Account.create_account(customer, value, request.POST['account_balance'])

                    return overview_customers(request)
                except DatabaseError:
                    # Todo: Print error message
                    return render(request, 'employee_app/create_customer_account.html', context)
        except Profile.DoesNotExist:
            # Todo: Print error message
            return render(request, 'employee_app/create_customer_account.html', context)   

    return render(request, 'employee_app/create_customer_account.html', context)

employee_app/templates/employee_app/create_customer.html
{% extends "auth_app/base.html" %}
{% block content %}

    <h3> Create Customer </h3>
    <form action="{% url 'employee_app:create_customer' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Enter Username" />
        <input type="text" name="first_name" placeholder="Enter First Name" />
        <input type="text" name="last_name" placeholder="Enter Last Name" />
        <input type="email" name="email" placeholder="Enter Email" />
        <input type="password" name="password1" placeholder="Password" />
        <input type="password" name="password2" placeholder="Repeat Password" />
        <select name="customer_rank">
            <option value="bronze">Bronze</option>
            <option value="silver">Silver</option>
            <option value="gold">Gold</option>
        </select>
        <input type="number" name="customer_phone_number" placeholder="Phone Number" />
        <label>Customer can loan:</label>
        <input type="checkbox" name="customer_has_loan">        
        <button>Create Customer</button>
    </form>
    {{ customerFormErrors.errors }}

{% endblock %}

employee_app/templates/employee_app/create_customer_account.html
{% extends "auth_app/base.html" %}
{% block content %}

    <h3> Create Customer Account </h3>
    <form action="{% url 'employee_app:create_customer_account' %}" method="POST">
        {% csrf_token %}
        <select name='account_user_fk'>
            {% for customer in customers %}
            <option value={{customer.id}}>{{customer.id}} {{customer.user.first_name}} {{customer.user.last_name}}</option>
            {% endfor %}
        </select>
        <!-- Todo: autogenerate -->
        <input type="number" name="account_balance" placeholder="Enter Account Balance" />
        <button>Create Customer Account</button>
    </form>
    {{ customerFormErrors.errors }}

{% endblock %}

employee_app/templates/employee_app/edit_customer.html
{% extends "auth_app/base.html" %}
{% block content %}

    <h3> Edit Customer </h3>
    <form action="{% url 'employee_app:edit_customer' customer.id %}" method="POST">
        {% csrf_token %}
        <input type="text" name="id" hidden value="{{ customer.id }}" />
        <input type="text" name="username" disabled placeholder="Enter Username" value="{{ customer.user.username }}"/>
        <input type="text" name="first_name" disabled placeholder="Enter First Name" value="{{ customer.user.first_name }}"/>
        <input type="text" name="last_name" disabled placeholder="Enter Last Name" value="{{ customer.user.last_name }}"/>
        <input type="email" name="email" placeholder="Enter Email" value="{{ customer.user.email }}" />
        <select name="customer_rank">
            <option value="bronze" {% if customer.customer_rank == 'bronze' %}selected="selected"{% endif %} >Bronze</option>
            <option value="silver" {% if customer.customer_rank == 'silver' %}selected="selected"{% endif %}>Silver</option>
            <option value="gold" {% if customer.customer_rank == 'gold' %}selected="selected"{% endif %}>Gold</option>
        </select>
        <input type="number" name="customer_phone_number" placeholder="Phone Number" value="{{ customer.customer_phone_number }}" />
        <label>Customer can loan:</label>
        <input type="checkbox" name="customer_has_loan" {% if customer.customer_has_loan %} checked {% else %} '' {% endif %}>  
        <button>Edit Customer</button>
    </form>

    {{ customerFormErrors.errors }}

{% endblock %}

employee_app/templates/employee_app/edit_customer_account.html
{% extends "auth_app/base.html" %}
{% block content %}

    <h4> Edit {{customer.user.last_name}} {{ customer.user.first_name }}'s Account Number {{ account.account_number }}</h4>
    <form action="{% url 'employee_app:edit_customer_account' customer.id account.id %}" method="POST">
        {% csrf_token %}
        <input type="text" name="customer_id" hidden value="{{ customer.id }}" />
        <input type="text" name="account_id" hidden value="{{ account.id }}" />
        <label>Balance</label>
        <input type="text" name="account_balance" value="{{ account.account_balance }}" placeholder="Edit Balance" />
        <br/>
        <p><b>Ongoing Loans</b></p>
        {% for loan in loansOngoing %}
        <p>Date: {{ loan.loan_date }} | Amount: {{ loan.loan_amount }} | Remain: {{ loan.loan_remain }} | Description: {{ loan.loan_description }}</p>
        {% endfor %}
        <p><b>Loans Payments</b></p>
        <p><b>Finished Loans</b></p>
        {% for loan in loansFinished %}
        <p>Date: {{ loan.loan_date }} | Amount: {{ loan.loan_amount }} | Remain: 0 | Description: {{ loan.loan_description }}</p>
        {% endfor %}
        <p><b>Account Transactions</b></p>
        {% for transaction in transactions %}
        <p>Date: {{ transaction.transaction_date }} | Amount: {{ transaction.transaction_amount }} | Currency: {{ transaction.transaction_currency }} | Receiver: {{ transaction.transaction_account_number_receiver }}</p>
        {% endfor %}
        <button>Edit Balance</button> 
    </form>

    {{ customerFormErrors.errors }}

{% endblock %}

employee_app/templates/employee_app/overview_customers.html
{% extends "auth_app/base.html" %}
{% block content %}

    <h3> All Customers </h3>
    <!-- Todo: check if new_user and edited_user exists -->
    {% if new_user %}
    <p>New user: {{ new_user }}</p>
    {% endif %}
    {% if edited_user %}
    <p>Edited user: {{ edited_user }}</p>
    {% endif %}
    {% if edited_account %}
    <p>Edited account: {{ edited_account }}</p>
    {% endif %}
    <hr>
    {% for customer in customers %}
        {% if customer.user.is_staff == False %}
        <h5 style="margin-top: 30px"> Customer: </h5>

        <table class="table">
            <thead>
            <tr>
                <th scope="col">First Name</th>
                <th scope="col">Phone Number</th>
                <th scope="col">Customer Rank</th>
                <th scope="col">Customer Loan</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">{{ customer.user }}</th>
                <td>{{ customer.customer_phone_number }}</td>
                <td>{{ customer.customer_rank }}</td>
                <td>{{ customer.customer_has_loan}}</td>
                <td><a href="/employee/edit_customer/{{customer.id}}"> Edit customer </a></td>
            </tr>
            </tbody>
        </table>

        <h5> Customer Accounts: </h5>
        
            
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Account Number</th>
                        <th scope="col">Account Balance</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for account in accounts %}
                        {% if account.account_user_fk == customer %}
                        <tr>
                            <th scope="row">{{ account.account_number }}</th>
                            <td>{{ account.account_balance }}</td>
                            <td><a href="/employee/edit_customer_account/{{customer.id}}/{{account.id}}"> Edit account </a></td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </tbody>
                </table>

        {% endif %}
    {% endfor %}

{% endblock %}