accounts_app_account/urls.py
from django.urls import path
from . import views

app_name = 'accounts_app_account'

urlpatterns = [
    path('', views.accounts_view, name='index'),
]

api/urls.py
from django.urls import path
from .views import CurrencyList, SymbolList, RateList
from .views import api_rate, api_currency_detail, api_rate_historical_from, api_rate_historical_range, api_convert
from .views import api_rate_historical_post, api_currency_update

app_name = 'api'

urlpatterns = [
    path('symbols/', SymbolList.as_view()),
    path('latest/', CurrencyList.as_view()),
    path('latest/<str:currency_code>/', api_currency_detail, name="detail"),
    path('rates/', RateList.as_view()),
    path('create/', api_rate_historical_post, name="create"),
    path('update/<str:currency_code>/', api_currency_update, name="edit"),
    path('rates/<str:rate_code>/', api_rate),
    path('rates/<str:rate_code>/<int:rate_from>/', api_rate_historical_from),
    path('rates/<str:rate_code>/<int:rate_from>/<int:rate_to>/', api_rate_historical_range),
    path('convert/<str:rate_code_from>/<str:rate_code_to>/<int:amount>/', api_convert),
]

auth_app/urls.py
from django.urls import path
from . import views

app_name = 'auth_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard')
]

banking_system/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

API_TITLE = 'Currency API'
API_DESCRIPTION = 'A web API for creating and editing blog posts.'
schema_view = get_schema_view(title="Blog API")

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),
    # Apps
    path('auth/', include('auth_app.urls')),
    path('transaction/', include('transaction_app.urls')),
    path('account/', include('accounts_app_account.urls')),
    path('employee/', include('employee_app.urls')),
    # path('auth/', include('django.contrib.auth.urls')),
    path('chat/', include('chat.urls')),
    # API
    path('api/v1/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    # Task queues
    path('celery-progress/', include('celery_progress.urls')),
    #MFA
    path('settings/', include('django_mfa.urls')),
    # Documentation
    path('documentation/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION))
]

employee_app/urls.py
from django.urls import path
from . import views
from auth_app.views import login,signup
# from django.views.generic import RedirectView
app_name = 'employee_app'

urlpatterns = [
    path('overview_customers/', views.overview_customers, name='overview_customers'),
    path('edit_customer/<int:customer_id>/', views.edit_customer, name='edit_customer'),
    path('edit_customer_account/<int:customer_id>/<int:customer_account_id>/' , views.edit_customer_account, name='edit_customer_account'),
    path('create_customer/', views.create_customer, name='create_customer'),
    path('create_customer_account/', views.create_customer_account, name='create_customer_account'),
    path('login/', login, name='employee_login'),
    path('signup/', signup, name='employee_signup'),
    # path('login/', RedirectView.as_view(pattern_name='auth_app:login')),
    # path('signup/', RedirectView.as_view(pattern_name='auth_app:signup')),
]

transaction_app/urls.py
from django.urls import path
from . import views

app_name = 'transaction_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.transaction_view, name='transaction'),
    path('transactions/', views.transactions_view, name='transactions'),
    path('confirmation/', views.confirmation_view, name='confirmation'),
    path('loan/', views.loan_view, name='loan'),
    path('payment/', views.loan_payment, name='payment'),
]

auth_app/models.py
from django.contrib.auth.models import User
from django.db import models

# Customizations for the user
class Profile(models.Model):
    RANK_CHOICES = [
        ('gold', 'Gold'),
        ('silver', 'Silver'),
        ('bronze', 'Bronze')
    ]

    # user = User.objects.create_user('username', first_name='positional-arg', last_name='positional-arg')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    customer_rank = models.CharField(max_length=10, choices=RANK_CHOICES, default='bronze')
    customer_phone_number = models.CharField(max_length=20)
    customer_token = models.CharField(max_length=256)
    # # Multi factor enabled
    customer_mfe = models.BooleanField(blank=False)
    customer_has_loan = models.BooleanField(blank=False)

    # Converts Python obj into strings
    def __str__(self):
        # Returning self would get an infinite loop
        return f"{self.user} | {self.customer_phone_number} | {self.customer_rank} | { True if self.customer_has_loan else False}"

    @classmethod
    def create_profile(self, user, phone, token, mfe, has_loan):
        profile = Profile.objects.create(user = user, 
                                         customer_phone_number = phone,
                                         customer_token = token, 
                                         customer_mfe = mfe, 
                                         customer_has_loan = has_loan)

        profile.save()
        return profile

    @classmethod
    def create_customer(self, email, username, password, first_name, last_name) -> User:
        user = User.objects.create_user(email = email, 
                                        username = username, 
                                        password = password, 
                                        first_name = first_name, 
                                        last_name = last_name)

        return user

    @classmethod
    def create_employee(self, email, username, password, first_name, last_name) -> User:
        user = User.objects.create_user(email = email, 
                                        username = username, 
                                        password = password, 
                                        first_name = first_name, 
                                        last_name = last_name,
                                        is_staff = True)

        return user

auth_app/forms.py
from django.contrib.auth.forms import UserCreationForm
# Equivalent: from django.forms import ModelForm
from django import forms
from .models import Profile

# SignupUserForm inherits from UserCreationForm
class SignupUserForm(UserCreationForm):
    # As UserCreationForm provides only 3 params 
    # username, password1, password2 we create the others
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(max_length=100, required=True)

    fields = [
        'username',
        'first_name',
        'last_name',
        'email',
        'password1',
        'password2',
    ]


class SignupProfileForm(forms.ModelForm):
    # The Meta class has two functions:
    # 1. Indicate which model we are using
    # 2. Show the fields we want to include in our final form
    class Meta:
        model = Profile

        # Customizing label for mfe
        labels = {
            'customer_mfe': 'Multi-factor auth enabled'
        }

        fields = [
            'customer_phone_number',
            'customer_mfe'
        ]

class LoginForm(forms.Form):
    # LoginForm has to be without model otherwise it takes validations
    # from the user model which implies that is_valid() will fail

    username = forms.CharField(label="Write your username", max_length=100)
    password = forms.CharField(label="Password", max_length=100)

    fields = [
        'username',
        'password'
    ]

auth_app/views.py
# from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login as loginUser, logout as logoutUser
from .forms import SignupProfileForm, SignupUserForm, LoginForm
from django.contrib.auth.models import User
from .models import Profile
from api.models import Currency
from django.db import transaction, DatabaseError
from django.contrib.auth.decorators import login_required
from accounts_app_account.models import Account
from django.urls import resolve
import random
import string


@login_required(login_url='/auth/login/')
def dashboard(request):
    currencies = Currency.objects.all()

    context = {
        'rates': currencies
    }

    return render(request, 'auth_app/dashboard.html', context)

def logout(request):
    # Calls also flush() which removes session data
    logoutUser(request)
    return HttpResponseRedirect(reverse('auth_app:login'))

def login(request):
    form = LoginForm(None)
    # Uses context to pass data
    # form.as_p renders as paragraphs 
    context = {
        'form': form
    }
    
    # admin3 and test 
    if request.method == "POST":
        loginForm = LoginForm(data=request.POST)
        if loginForm.is_valid():
            userObject = authenticate(request, username=request.POST['username'], password=request.POST['password']) 
            if userObject:
                loginUser(request, userObject)
                # Todo: get user rank
                # context = {
                #     'username': request.POST['username']
                # }
                # First / cleans up the URL clean following the paths in urls.py
                # return render(request, 'auth_app/dashboard.html', context)

                # The previous does not change route, we pass context in session
                user = User.objects.get(username=userObject)
                request.session['is_staff'] = user.is_staff
                request.session['username'] = request.POST['username']
                return HttpResponseRedirect(reverse('auth_app:dashboard'))
            else:
                context = {
                    'form': form,
                    'error': 'Incorrect login data'
                }
                return render(request, 'auth_app/login.html', context)
        else:
            context = {
                'form': loginForm,
                'error': 'Invalid form'
            }

    # First argument = request object
    # Second argument = template string
    # Third argument = data dictionary
    return render(request, 'auth_app/login.html', context)


def signup(request):
    # https://stackoverflow.com/questions/59133456/how-to-add-2-models-in-a-registration-form-in-django
    signup_user = SignupUserForm()
    profile_user = SignupProfileForm()
    context = {
        'signup_user': signup_user,
        'profile_user': profile_user
    }

    # current_url = resolve(request.path_info).url_name
    # print(current_url)

    if request.method == "POST":
        # This:
        # print(request.POST)
        # Prints this:
        # <QueryDict: {'csrfmiddlewaretoken': ['A0390Q8p7lzY50KSCbWpfs1hW7T40G8I5zhYYliyyHbAd1oaSTq9gkSlYHxEHCh0'], 'username': ['root'], 'first_name': [''], 'last_name': [''], 'email': [''], 'password1': ['v!rbeK9kHj6uLTh'], 'password2': ['v!rbeK9kHj6uLTh'], 'customer_rank': ['gold']}>
        signupForm = SignupUserForm(request.POST)
        if signupForm.is_valid():
            # No password verification because that is provided out of the box
            profileForm = SignupProfileForm(request.POST)
            if profileForm.is_valid():
                post_username = request.POST['username']
                post_fname = request.POST['first_name']
                post_lname = request.POST['last_name']
                post_email = request.POST['email']
                post_password = request.POST['password1']
                post_phone = request.POST['customer_phone_number']
                # MultiValueDict's get fetches a value and provides a default
                post_mfe = request.POST.get('customer_mfe', False)
                post_mfe = True if post_mfe == 'on' else False
                # post_mfe = True if request.POST['customer_mfe'] == 'on' else False

                # exception = True
                current_url = resolve(request.path_info).url_name
                # Transactions: https://django.cowhite.com/blog/customizing-user-details-user-models-and-authentication/
                try:
                    with transaction.atomic():
                        # create_user() hashes the password
                        if(current_url == 'signup'):
                            user = Profile.create_customer(post_email, post_username, post_password, post_fname, post_lname)
                            
                        else:
                            user = Profile.create_employee(post_email, post_username, post_password, post_fname, post_lname)

                        # create() does not hash 
                        profile = Profile.create_profile(user, post_phone, '123token', post_mfe, False)
                        
                        letters = string.digits
                        value = ( ''.join(random.choice(letters) for i in range(20)) )
                        
                        account = Account.create_account(profile, value, 0.00)

                        # Test exception:
                        # if exception:
                        #     raise exception
                except DatabaseError:
                    print("Transaction failed")
                    pass
                
                # If it succeeds
                # context = {
                #     'username': post_username
                # }

                # Needed for recognizing is_staff bool
                userObject = authenticate(request, username=post_username, password=post_password) 
                user = User.objects.get(username=userObject)

                request.session['is_staff'] = user.is_staff
                request.session['username'] = post_username
                loginUser(request, authenticate(request, username=post_username, password=post_password))
                return HttpResponseRedirect(reverse('auth_app:dashboard'))
            
            else: 
                context = {
                    'signup_user': signup_user,
                    'profile_user': profileForm
                }
        else:
            context = {
                'signup_user': signupForm,
                'profile_user': profile_user
            }
    return render(request, 'auth_app/signup.html', context)

# Migrations issues:
# https://stackoverflow.com/questions/34548768/django-no-such-table-exception

# Todo: admin view models enabled
# Todo: check routing for logging in url

auth_app/templates/auth_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>BankingSystem - Authentication</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  <!-- CSS CUSTOM -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'auth_app:dashboard' %}">Banking System</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" aria-current="page"  href="{% url 'auth_app:dashboard' %}">Home</a>
          </li>
          {% if not request.session.is_staff %}
          {% if request.session.username %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts_app_account:index' %}"> Profile </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'transaction_app:index' %}"> Transactions/Loans</a>
          </li>
          {% endif %}
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'employee_app:overview_customers' %}">View All Customers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'employee_app:create_customer' %}">Create New Customer</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'employee_app:create_customer_account' %}">Create New Customer Account</a>
          </li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav">
          {% if not request.session.username %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'auth_app:login' %}"> Login </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_app:signup' %}"> Signup </a>
          </li>
          {% endif %}
          {% if request.session.username %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'auth_app:logout' %}">Logout</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

    <div class='container mt-5 mx-auto row'>
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

auth_app/templates/auth_app/dashboard.html
{% extends './base.html' %}
{% load timetags %}
{% block content %}

    <h3 class="mb-5">Dashboard</h3>

    <div class="container">
        <div class="row">
            <div class="col-4">
                <p> Hello, {{ request.session.username }} ! </p>
            </div>
            <div class="col-8">
                <table class="table table-striped table-dark">
                    <thead>
                      <tr>
                        <th scope="col">Flag</th>
                        <th scope="col">Currency</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Symbol</th>
                        <th scope="col">Date</th>
                      </tr>
                    </thead>
                    <tbody>
                        <tr class="table-success"> 
                            <td><img width="30px" height="20px" src='https://www.worldometers.info/img/flags/us-flag.gif' /></td>
                            <th scope="row">USD</th>
                            <td>1</td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tbody>
                    <tbody>
                      {% for currency in rates %}
                        {% if currency.currency_code != 'USD' %}
                            <tr> 
                                <td><img width="30px" height="20px" src={{ currency.currency_image }} /></td>
                                <th scope="row">{{ currency.currency_code }}</th>
                                <td>{{ currency.currency_rate }}</td>
                                <td>{{ currency.currency_symbol }}</td>
                                <td>{{ currency.currency_timestamp|print_timestamp }}</td>
                            </tr>
                        {% endif %}
                      {% endfor %}
                    </tbody>
            
                </table> 
            </div>
        </div>
    </div>
    
    


{% endblock %}

auth_app/templates/auth_app/login.html
{% extends './base.html' %}

{% block content %}
    {% if request.path == '/auth/login/' %}
    <h3 class="mb-5">Welcome to Bank Customer Login</h3>
    <p><b>Are you an employee? Go to employee login <a href="{% url 'employee_app:employee_login' %}">here</a></b></p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.errors }}
        {{ error }}
        <button type="submit">Log In</button>
    </form>
    {% else %}
    <h3 class="mb-5">Welcome to Bank Employee Login</h3>
    <p><b>Are you an customer? Go to customer login <a href="{% url 'auth_app:login' %}">here</a></b></p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.errors }}
        {{ error }}
        <button type="submit">Log In</button>
    </form>
    {% endif %}
{% endblock %}

auth_app/templates/auth_app/signup.html
{% extends './base.html' %}

{% block content %}
    {% if request.path == '/auth/signup/' %}
        <h3 class="mb-5">Welcome to Bank Customer Signup</h3>
        <p><b>Are you an employee? Go to employee signup <a href="{% url 'employee_app:employee_signup' %}">here</a></b></p>
        <form class="container" method="post">
            {% csrf_token %}

            {% for field in signup_user %}
            <div class="row">
                
                <div class="col-25">
                    {{ field.label_tag }} 
                </div>
                <div class="col-75">
                    {{ field }}
                </div>
                <div> {{ field.errors }} </div>
                <!-- {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %} -->
            </div>
            {% endfor%}

            {% for field in profile_user %}
            <div class="row">
                
                <div class="col-25">
                    {{ field.label_tag }} 
                </div>
                <div class="col-75" style="display: flex; align-items: center;">
                    {{ field }}
                </div>
                <div> {{ field.errors }} </div>
                <!-- {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %} -->
            </div>
            {% endfor%}
          
            <button type="submit" style="margin-left: 91%;">Sign Up</button>
        </form>
    {% else %}
        <!-- <h3 class="mb-5">Welcome to Bank Customer Singnup</h3>
        <p><b>Are you an customer? Go to customer signup <a href="{% url 'auth_app:signup' %}">here</a></b></p>
        <form method="post">
            {% csrf_token %}
            {{ signup_user.as_p }}
            {{ profile_user.as_p }}
            {{ signup_user.errors }}
            {{ profile_user.errors }}
            <button type="submit">Sign Up</button>
        </form> -->
        <h3 class="mb-5">Welcome to Bank Employee Signup</h3>
        <p><b>Are you an customer? Go to customer signup <a href="{% url 'auth_app:signup' %}">here</a></b></p>
        <form class="container" method="post">
            {% csrf_token %}

            {% for field in signup_user %}
            <div class="row">
               
                <div class="col-25">
                    {{ field.label_tag }} 
                </div>
                <div class="col-75">
                    {{ field }}
                </div>
                <div> {{ field.errors }} </div>
                <!-- {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %} -->
            </div>
            {% endfor%}

            {% for field in profile_user %}
            <div class="row">
               
                <div class="col-25">
                    {{ field.label_tag }} 
                </div>
                <div class="col-75" style="display: flex; align-items: center;">
                    {{ field }}
                </div>
                <div> {{ field.errors }} </div>
                <!-- {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %} -->
            </div>
            {% endfor%}
          
            <button type="submit" style="margin-left: 91%;">Sign Up</button>
        </form>
    {% endif %}
{% endblock %}