accounts_app_account/urls.py
from django.urls import path
from . import views

app_name = 'accounts_app_account'

urlpatterns = [
    path('', views.accounts_view, name='index'),
]

api/urls.py
from django.urls import path
from .views import CurrencyList, SymbolList, RateList
from .views import api_rate, api_currency_detail, api_rate_historical_from, api_rate_historical_range, api_convert
from .views import api_rate_historical_post, api_currency_update

app_name = 'api'

urlpatterns = [
    path('symbols/', SymbolList.as_view()),
    path('latest/', CurrencyList.as_view()),
    path('latest/<str:currency_code>/', api_currency_detail, name="detail"),
    path('rates/', RateList.as_view()),
    path('create/', api_rate_historical_post, name="create"),
    path('update/<str:currency_code>/', api_currency_update, name="edit"),
    path('rates/<str:rate_code>/', api_rate),
    path('rates/<str:rate_code>/<int:rate_from>/', api_rate_historical_from),
    path('rates/<str:rate_code>/<int:rate_from>/<int:rate_to>/', api_rate_historical_range),
    path('convert/<str:rate_code_from>/<str:rate_code_to>/<int:amount>/', api_convert),
]

banking_system/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

API_TITLE = 'Currency API'
API_DESCRIPTION = 'A web API for creating and editing blog posts.'
schema_view = get_schema_view(title="Blog API")

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),
    # Apps
    path('auth/', include('auth_app.urls')),
    path('transaction/', include('transaction_app.urls')),
    path('account/', include('accounts_app_account.urls')),
    path('employee/', include('employee_app.urls')),
    # path('auth/', include('django.contrib.auth.urls')),
    path('chat/', include('chat.urls')),
    # API
    path('api/v1/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    # Task queues
    path('celery-progress/', include('celery_progress.urls')),
    #MFA
    path('settings/', include('django_mfa.urls')),
    # Documentation
    path('documentation/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION))
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

accounts_app_account/models.py
from django.db import models
from auth_app.models import Profile
# Create your models here.
class Account(models.Model):
    account_user_fk = models.ForeignKey(Profile, on_delete=models.PROTECT)
    account_number = models.CharField(max_length=20, null=False)
    account_balance = models.DecimalField(decimal_places=2,max_digits=7, default=0)

    def __str__(self):
        # Returning string of the id
        return f"Number {self.account_number} - Name:{self.account_user_fk} - Balance: {self.account_balance}"

    @classmethod
    def create_account(self, profile, value, balance):
        account = Account.objects.create(account_user_fk=profile,
                                         account_number=value,
                                         account_balance=balance)

        account.save()
        return account

accounts_app_account/views.py
from django.shortcuts import render

from .models import Account 
from transaction_app.models import Transaction
from auth_app.models import Profile

def accounts_view(request):
    user = request.user
    # path = request.path
    # print(path)
    profile = Profile.objects.get(user=user)
    user_account = Account.objects.filter(account_user_fk=profile)

    context = {
        "user": user,
        "user_accounts": user_account,
        "profile": profile
    }
    return render(request, "accounts_app_account/account.html", context)

accounts_app_account/templates/accounts_app_account/account.html
{% extends "auth_app/base.html" %}



{% block content %}
    <div style="display: flex; flex-wrap:nowrap; align-items: center;">
      <h3 style="display: inline"> Account Overview</h3>
      <p class={{ profile.customer_rank }} style='margin: 10px 30px; padding: 5px 15px;'>{{ profile.customer_rank| title }}</p>    
    </div>
    
    <p style="margin: 20px 0px;">Hello <b>  {{ user }} </b> , here is your information: </p> 
    <!-- <small class="badge badge-pill badge-primary"> <a href="/auth/dashboard" > Go dashboard</a></small> -->

    {% if profile.customer_rank != 'gold' %}
      <p>It seems your account's rank is not gold. This prevents you from being able to get a loan. Do you want an upgrade? Click <a href="{% url 'chat:index' %}">here</a> to chat with one of our employees.</p>
    {% endif %}

    <span> We <b>strongly</b> suggest to activate the multifactor authentification <a href="/settings/mfa/configure/"> here</a>.</span>
    
    <p></p>

    <div>
        <p> <b> Username:</b> {{user.username}} </p>
        <p> <b> Email: </b>  {{user.email}}</p>
        <p> <b> Phone: </b> {{customer.customer_phone_number}} </p>
    </div>
    <table class="table">
        <thead>
            <tr>
              <th scope="col">Account Number</th>
              <th scope="col">Account Balance</th>
              <th scope="col"> Account Type </th>
              <th scope="col">  </th>
            </tr>
          </thead>
            {% for account in user_accounts %}
            <tbody>
                <tr>
                  <td>{{  account.account_number }}</td>
                  <td> DKK {{account.account_balance}}</td>
                  <td> {{profile.customer_rank}} </td>
                  <td>  </td>
                </tr>
            </tbody>
            {% endfor %}
        </ul>

        
    
        
{% endblock %}